# Fase 0 - Ingesta de datos

In [3]:
import os
from urllib.request import urlretrieve

In [4]:
if not os.path.exists("../data"):
    os.makedirs("../data")

## Descargar Datasets Abiertos

![](../img/DownloadOpenData.png)

### Paso 1: Descargar datos

In [8]:
# source: https://data.imdb.com/non-commercial-datasets/

urlretrieve(
    "https://datasets.imdbws.com/title.basics.tsv.gz", 
    "../data/title.basics.tsv.gz"
)
    
urlretrieve(
    "https://datasets.imdbws.com/title.ratings.tsv.gz", 
    "../data/title.ratings.tsv.gz"
)

('../data/title.ratings.tsv.gz', <http.client.HTTPMessage at 0xfffee3446ae0>)

In [1]:
!uv add polars

Resolved 3 packages in 0.88ms
Checked 2 packages in 0.06ms

In [2]:
import polars as pl
pl.__version__

'2.1.0'

### Paso 2: Lectura de datos

#### A) Basics Data

In [9]:
basics_df = pl.read_csv(
    "../data/title.basics.tsv.gz",
    separator="\t",
    null_values="\\N", # to handle missing values
    quote_char=None,   # to avoid issues with quotes in the data
)

In [10]:
basics_df.head()

shape: (5, 9)
┌───────────┬───────────┬────────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ tconst    ┆ titleType ┆ primaryTit ┆ originalT ┆ … ┆ startYear ┆ endYear ┆ runtimeMi ┆ genres    │
│ ---       ┆ ---       ┆ le         ┆ itle      ┆   ┆ ---       ┆ ---     ┆ nutes     ┆ ---       │
│ str       ┆ str       ┆ ---        ┆ ---       ┆   ┆ i64       ┆ str     ┆ ---       ┆ str       │
│           ┆           ┆ str        ┆ str       ┆   ┆           ┆         ┆ i64       ┆           │
╞═══════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ tt0000001 ┆ short     ┆ Carmencita ┆ Carmencit ┆ … ┆ 1894      ┆ null    ┆ 1         ┆ Documenta │
│           ┆           ┆            ┆ a         ┆   ┆           ┆         ┆           ┆ ry,Short  │
│ tt0000002 ┆ short     ┆ Le clown   ┆ Le clown  ┆ … ┆ 1892      ┆ null    ┆ 5         ┆ Animation │
│           ┆           ┆ et ses     ┆ et ses    ┆   ┆           ┆         ┆           ┆ ,Short    │
│           ┆           ┆ chiens     ┆ chiens    ┆   ┆           ┆         ┆           ┆           │
│ tt0000003 ┆ short     ┆ Poor       ┆ Pauvre    ┆ … ┆ 1892      ┆ null    ┆ 5         ┆ Animation │
│           ┆           ┆ Pierrot    ┆ Pierrot   ┆   ┆           ┆         ┆           ┆ ,Comedy,R │
│           ┆           ┆            ┆           ┆   ┆           ┆         ┆           ┆ omance    │
│ tt0000004 ┆ short     ┆ Un bon     ┆ Un bon    ┆ … ┆ 1892      ┆ null    ┆ 12        ┆ Animation │
│           ┆           ┆ bock       ┆ bock      ┆   ┆           ┆         ┆           ┆ ,Short    │
│ tt0000005 ┆ short     ┆ Blacksmith ┆ Blacksmit ┆ … ┆ 1893      ┆ null    ┆ 1         ┆ Short     │
│           ┆           ┆ Scene      ┆ h Scene   ┆   ┆           ┆         ┆           ┆           │
└───────────┴───────────┴────────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [11]:
# how many rows and columns are in the dataframe
basics_df.shape

(12902085, 9)

#### B) Ratings Data

In [13]:
ratings_df = pl.read_csv(
    "../data/title.ratings.tsv.gz",
    separator="\t",
    null_values="\\N", # to handle missing values
    quote_char=None,   # to avoid issues with quotes in the data
)
ratings_df.head()

shape: (5, 3)
┌───────────┬───────────────┬──────────┐
│ tconst    ┆ averageRating ┆ numVotes │
│ ---       ┆ ---           ┆ ---      │
│ str       ┆ f64           ┆ i64      │
╞═══════════╪═══════════════╪══════════╡
│ tt0000001 ┆ 5.7           ┆ 2238     │
│ tt0000002 ┆ 5.4           ┆ 327      │
│ tt0000003 ┆ 6.4           ┆ 2401     │
│ tt0000004 ┆ 5.0           ┆ 203      │
│ tt0000005 ┆ 6.2           ┆ 3104     │
└───────────┴───────────────┴──────────┘

In [14]:
ratings_df.shape

(1726141, 3)

#### C) Unificar Datasets

In [15]:
# merge the two dataframes on the tconst column, which is the unique identifier for each title in the IMDB dataset
movies_df = (
    basics_df
    .filter(pl.col("titleType") == "movie")  # filter for movies only
    .select([
        pl.col("tconst").alias("imdb_movie_id"), # rename the column to imdb_movie_id
        pl.col("primaryTitle").alias("title"), # rename the column to title
        pl.col("startYear").cast(pl.Int32).alias("year"), # rename the column to year and cast it to Int32
        pl.col("genres") # keep the genres column
    ])
    .join(
        ratings_df.select(["tconst", "averageRating", "numVotes"]), # select only the necessary columns from ratings_df
        left_on="imdb_movie_id",    # join on the imdb_movie_id column from basics_df
        right_on="tconst"           # join on the tconst column from ratings_df
    )
    .rename({       # rename columns in the merged dataframe
        "averageRating": "imdb_rating", # rename the column to imdb_rating
        "numVotes": "imdb_votes"        # rename the column to imdb_votes
    })
    .filter(
        (pl.col("imdb_votes") >= 1000)   # filter for movies with at least 1000 votes
    )
)

In [16]:
movies_df.head()

shape: (5, 6)
┌───────────────┬───────────────────┬──────┬────────────────────────────┬─────────────┬────────────┐
│ imdb_movie_id ┆ title             ┆ year ┆ genres                     ┆ imdb_rating ┆ imdb_votes │
│ ---           ┆ ---               ┆ ---  ┆ ---                        ┆ ---         ┆ ---        │
│ str           ┆ str               ┆ i32  ┆ str                        ┆ f64         ┆ i64        │
╞═══════════════╪═══════════════════╪══════╪════════════════════════════╪═════════════╪════════════╡
│ tt0000574     ┆ The Story of the  ┆ 1906 ┆ Action,Adventure,Biography ┆ 6.0         ┆ 1102       │
│               ┆ Kelly Gang        ┆      ┆                            ┆             ┆            │
│ tt0002130     ┆ Dante's Inferno   ┆ 1911 ┆ Adventure,Drama,Fantasy    ┆ 7.1         ┆ 4341       │
│ tt0002423     ┆ Passion           ┆ 1919 ┆ Biography,Drama,Romance    ┆ 6.7         ┆ 1146       │
│ tt0002844     ┆ Fantômas: In the  ┆ 1913 ┆ Crime,Drama                ┆ 6.9         ┆ 2778       │
│               ┆ Shadow of the…    ┆      ┆                            ┆             ┆            │
│ tt0003014     ┆ Ingeborg Holm     ┆ 1913 ┆ Drama                      ┆ 7.0         ┆ 1642       │
└───────────────┴───────────────────┴──────┴────────────────────────────┴─────────────┴────────────┘

In [17]:
movies_df.write_parquet(
    "../data/movies.parquet",
    compression="snappy", # use snappy compression for faster read/write
)

In [18]:
movies_df.shape

(49392, 6)

#### D) Guardar IDs de películas

In [24]:
# write the imdb_movie_id column to a text file, one id per line
with open("../data/movie_ids.txt", "w") as f:
    for movie_id in movies_df["imdb_movie_id"].to_list():
        f.write(f"{movie_id}\n")

In [25]:
!head ../data/movie_ids.txt

tt0000574
tt0002130
tt0002423
tt0002844
tt0003014
tt0003037
tt0003165
tt0003419
tt0003643
tt0003740

## Descargar Dataset Privado de OMDB API

![](../img/DownloadPrivateData.png)

### Paso A) Configuración

In [20]:
# Source: https://www.omdbapi.com/
!uv add dotenv loguru aiohttp orjson tqdm

Resolved 20 packages in 801ms
Prepared 14 packages in 814ms                                                aiohttp              ------------------------------ 1.42 MiB/1.81 MiB           aiohttp              ------------------------------ 461.59 KiB/1.81 MiB         aiohttp              ------------------------------ 242.97 KiB/1.81 MiB         aiohttp              ------------------------------ 222.82 KiB/1.81 MiB         aiohttp              ------------------------------ 94.82 KiB/1.81 MiB          aiohttp              ------------------------------ 78.82 KiB/1.81 MiB          aiohttp              ------------------------------ 47.39 KiB/1.81 MiB          aiohttp              ------------------------------ 46.82 KiB/1.81 MiB          aiohttp              ------------------------------ 14.82 KiB/1.81 MiB          Aiohttp              ------------------------------     0 B/1.81 MiB
Installed 14 packages in 10ms
 + aiohappyeyeballs==2.7.1
 + aiohttp==3.14.5
 + aiosignal==1.4.0
 + attrs==26.1.0
 + dotenv==0.9.9
 + frozenlist==1.8.0
 + idna==3.20
 + loguru==0.7.3
 + multidict==7.2.1
 + orjson==3.13.0
 + propcache==0.5.4
 + python-dotenv==1.2.4
 + tqdm==4.70.1
 + yarl==1.25.1

In [21]:
from dotenv import load_dotenv
from loguru import logger
from tqdm import tqdm
from pathlib import Path

import aiohttp
import asyncio

import orjson

from typing import List, Dict

In [22]:
import os

# Cargar variables de entorno desde archivo .env (incluida la API KEY)
load_dotenv()

OMDB_API_KEY = os.getenv("OMDB_API_KEY")

In [26]:
# ========== CONFIGURACIÓN GLOBAL ==========
# URL base de la API de OMDb
OMDB_API_URL = "https://www.omdbapi.com/"
# Número de workers concurrentes para descargar datos en paralelo
# CONCURRENCY = 20
CONCURRENCY = 5
# Número máximo de reintentos por cada ID que falla
MAX_RETRIES = 5
# Ruta del archivo para guardar qué IDs ya fueron procesados
CHECKPOINT_FILE = "../data/processed_ids.txt"


# ========== CONFIGURACIÓN DE LOGURU ==========
# Eliminar los manejadores de logs por defecto
logger.remove()
# Agregar un nuevo manejador de logs con formato personalizado y colores
logger.add(
    lambda msg: tqdm.write(msg, end=""),  # Función que imprime el mensaje usando tqdm para no romper la barra de progreso
    # lambda msg: print(msg, end=""),  # Función que imprime el mensaje sin agregar salto de línea extra
    colorize=True,  # Habilitar colores en los logs
    format="<green>{time:HH:mm:ss}</green> | "  # Hora en verde
           "<level>{level}</level> | "  # Nivel de log (INFO, WARNING, etc.)
           "{message}\n",  # Mensaje del log
)

1

### Paso B: Checkpoint

In [27]:
# ========== UTILIDADES DE CHECKPOINT ==========
# Función para cargar IDs que ya fueron procesados
def load_processed_ids() -> set[str]:
    """Carga los IDs de IMDb ya procesados desde el archivo de checkpoint."""
    # Verificar si el archivo de checkpoint existe
    if Path(CHECKPOINT_FILE).exists():
        logger.info(f"Loading checkpoint from {CHECKPOINT_FILE}")
        # Abrir el archivo en modo lectura
        with open(CHECKPOINT_FILE, "r") as f:
            # Leer cada línea, eliminar espacios en blanco, y crear un conjunto
            return set(line.strip() for line in f if line.strip())
    # Si el archivo no existe, retornar un conjunto vacío
    return set()


# Función para guardar un ID procesado en el checkpoint
def append_processed_id(imdb_id: str) -> None:
    """Agrega un único ID de IMDb al archivo de checkpoint."""
    # Abrir el archivo en modo append (añadir al final)
    with open(CHECKPOINT_FILE, "a") as f:
        # Escribir el ID seguido de un salto de línea
        f.write(imdb_id + "\n")

### Paso C: Request a OMDB

In [28]:
# ========== FUNCIÓN PARA UN ÚNICO REQUEST A OMDb ==========
# Función asíncrona para obtener datos de una película de OMDb
async def fetch_one(session: aiohttp.ClientSession, imdb_id: str) -> Dict | None:
    """
    Obtiene un registro de OMDb por su ID de IMDb.
    Retorna: {"imdb_id": ..., "raw": <json_de_omdb>} o None si falla permanentemente.
    """
    # Definir los parámetros para el request a OMDb
    params = {
        "i": imdb_id,  # ID de IMDb (ej: tt1234567)
        "apikey": os.getenv("OMDB_API_KEY"),  # API key desde variables de entorno
        "plot": "full",  # Obtener la trama completa de la película
    }
    # Inicializar contador de reintentos
    retries = 0
    # logger.info(params)

    # Bucle que se ejecuta mientras no se alcance el máximo de reintentos
    while retries < MAX_RETRIES:
        try:
            # logger.info(f"[{imdb_id}] AFTER request")
            # Hacer un request GET asíncrono a la API
            async with session.get(OMDB_API_URL, params=params) as resp:
                # logger.info(f"[{imdb_id}] BEFORE request")
                # Obtener el código de estado HTTP
                status = resp.status

                # Manejar error 429: Too Many Requests (limite de rate)
                if status == 429:
                    # Calcular tiempo de espera: 5 segundos por reintento
                    wait = 5 * (retries + 1)
                    logger.warning(f"[{imdb_id}] 429 Too Many Requests — sleeping {wait}s")
                    # Esperar antes de reintentar
                    await asyncio.sleep(wait)
                    # Incrementar contador de reintentos
                    retries += 1
                    # Saltar a la siguiente iteración del bucle
                    continue

                # Manejar errores del servidor (5xx)
                if status >= 500:
                    # Calcular tiempo de espera: 3 segundos por reintento
                    wait = 3 * (retries + 1)
                    logger.warning(f"[{imdb_id}] Server error {status} — retrying in {wait}s")
                    # Esperar antes de reintentar
                    await asyncio.sleep(wait)
                    # Incrementar contador de reintentos
                    retries += 1
                    # Saltar a la siguiente iteración del bucle
                    continue

                # Convertir la respuesta a JSON
                data = await resp.json()

                # Verificar si OMDb retornó un error lógico (ID inválido, etc.)
                if data.get("Response") == "False":
                    # Obtener el mensaje de error de OMDb
                    err = data.get("Error", "Unknown error")
                    logger.error(f"[{imdb_id}] OMDb error: {err}")
                    # Retornar el resultado con el error (para guardar en log)
                    return {"imdb_id": imdb_id, "raw": data}

                # Si todo fue exitoso, retornar los datos (sin generar log para evitar spam)
                return {"imdb_id": imdb_id, "raw": data}

        # Manejar excepción de timeout
        except asyncio.TimeoutError:
            # Incrementar contador de reintentos
            retries += 1
            # Calcular tiempo de espera: 2 segundos por reintento
            wait = 2 * retries
            logger.warning(f"[{imdb_id}] Timeout — retrying in {wait}s")
            # Esperar antes de reintentar
            await asyncio.sleep(wait)

        # Manejar cualquier otra excepción inesperada
        except Exception as e:
            # Incrementar contador de reintentos
            retries += 1
            # Calcular tiempo de espera: 2 segundos por reintento
            wait = 2 * retries
            logger.error(f"[{imdb_id}] Unexpected error: {e} — retrying in {wait}s")
            # Esperar antes de reintentar
            await asyncio.sleep(wait)

    # Si se agotan todos los reintentos, registrar error crítico
    logger.critical(f"[{imdb_id}] FAILED permanently after {MAX_RETRIES} retries")
    # Retornar None para indicar fallo definitivo
    return None

### Paso D: Worker

In [29]:
# ========== WORKER: PROCESA IDs DE LA COLA Y ESCRIBE A JSONL ==========
# Función asíncrona que actúa como worker para procesar IDs en paralelo
async def worker(
    worker_id: int,  # Identificador del worker
    session: aiohttp.ClientSession,  # Sesión HTTP compartida
    queue: asyncio.Queue,  # Cola de IDs a procesar
    jsonl_path: Path,  # Ruta del archivo JSONL para guardar resultados
    write_lock: asyncio.Lock,  # Lock para escribir de forma segura en el archivo
    progress: tqdm # Barra de progreso opcional (para mostrar progreso en consola)
):
    # Bucle infinito que procesa IDs de la cola
    while True:
        # Obtener el siguiente ID de la cola (espera si está vacía)
        imdb_id = await queue.get()
        # Verificar si es la señal de terminación (None)
        if imdb_id is None:
            # Marcar la tarea como completada
            queue.task_done()
            # Salir del bucle para terminar el worker
            return

        # logger.info(f"Worker {worker_id}: {imdb_id}")

        # Obtener datos de OMDb para este ID
        result = await fetch_one(session, imdb_id)

        # Verificar si el fetch fue exitoso
        if result is not None:
            # Convertir el resultado a formato JSON y luego a string (usando orjson)
            line = orjson.dumps(result).decode("utf-8") + "\n"

            # Usar un lock para asegurar que solo un worker escriba a la vez
            async with write_lock:
                # Abrir el archivo JSONL en modo append
                with open(jsonl_path, "a", encoding="utf-8") as f:
                    # Escribir una línea JSON
                    f.write(line)

            # Guardar el ID como procesado en el checkpoint
            append_processed_id(imdb_id)
        
        # Actualizar la barra de progreso
        progress.update(1)

        # Marcar la tarea como completada en la cola
        queue.task_done()

### Paso E: Pipeline Asíncrono

In [30]:
# ========== FUNCIÓN PRINCIPAL: PIPELINE ASÍNCRONO ==========
# Función asíncrona principal que orquesta todo el descargador
async def main(
    all_ids: List[str],  # Lista de todos los IDs de IMDb a descargar
    output_file: str = "omdb_raw.jsonl",  # Ruta del archivo de salida JSONL
):
    """
    Punto de entrada principal del descargador de OMDb.
    
    - all_ids: lista de IDs de IMDb (formato: ttXXXXXX)
    - output_file: ruta del archivo JSONL para guardar los resultados
    
    Esta función:
    - Salta los IDs que ya fueron procesados
    - Descarga los IDs restantes con concurrencia
    - Guarda cada resultado como una línea JSON en output_file
    - Es segura para reintentar después de crashes
    """
    # Convertir el path a un objeto Path
    jsonl_path = Path(output_file)

    # Cargar los IDs que ya fueron procesados desde el checkpoint
    processed = load_processed_ids()
    # Crear una lista de IDs que aún no han sido procesados
    remaining = [i for i in all_ids if i not in processed]
    # Crear una barra de progreso para mostrar el avance de la descarga
    progress = tqdm(
        total=len(remaining),
        desc="Downloading OMDb",
        unit="movie",
        colour="green",
        dynamic_ncols=True,
    )

    # Registrar información sobre el progreso
    logger.info(f"Total IDs: {len(all_ids)}")
    logger.info(f"Already processed: {len(processed)}")
    logger.info(f"Remaining to fetch: {len(remaining)}")
    logger.info(f"Output JSONL: {jsonl_path}")

    # Si no hay IDs por procesar, salir de la función
    if not remaining:
        logger.success("Nothing to do. All IDs are already processed.")
        return

    # Crear una cola asíncrona para almacenar los IDs a procesar
    queue: asyncio.Queue = asyncio.Queue()
    # Crear un lock para sincronizar escrituras concurrentes
    write_lock = asyncio.Lock()

    # Encolar todos los IDs que falta procesar
    for imdb_id in remaining:
        await queue.put(imdb_id)

    # Configurar un timeout de 40 segundos para cada request HTTP
    timeout = aiohttp.ClientTimeout(total=40)

    # Crear una sesión HTTP asíncrona con el timeout configurado
    async with aiohttp.ClientSession(timeout=timeout) as session:
        # Crear y lanzar múltiples workers en paralelo
        workers = [
            asyncio.create_task(worker(i, session, queue, jsonl_path, write_lock, progress))
            for i in range(CONCURRENCY)
        ]

        # Encolar una señal de terminación (None) para cada worker
        for _ in workers:
            await queue.put(None)

        # Esperar hasta que todos los IDs de la cola hayan sido procesados
        await queue.join()

        # Cancelar cualquier worker que aún esté en ejecución
        for w in workers:
            w.cancel()

    # Cerrar la barra de progreso
    progress.close()

    # Registrar que la descarga completó exitosamente
    logger.success("Download complete.")
    logger.info(f"Results appended to {jsonl_path}")

#### Paso F: Ejecutar

In [ ]:
# ========== CARGAR LISTA DE IDs Y EJECUTAR EL DESCARGADOR ==========
with open("../data/movie_ids.txt") as f:
    # Leer todos los IDs de IMDb desde el archivo, eliminando espacios en blanco
    all_ids = [line.strip() for line in f if line.strip()]

# Run the async downloader
# await main(all_ids[:1500], output_file="../data/omdb_raw.jsonl")
await main(all_ids, output_file="../data/omdb_raw.jsonl")

Downloading OMDb:   0%|          | 0/1500 [00:00<?, ?movie/s]

16:59:16 | INFO | Total IDs: 1500

16:59:16 | INFO | Already processed: 0

16:59:16 | INFO | Remaining to fetch: 1500

16:59:16 | INFO | Output JSONL: ../data/omdb_raw.jsonl

Downloading OMDb:  67%|██████▋   | 1003/1500 [00:48<00:24, 20.66movie/s]

17:00:04 | ERROR | [tt0030755] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0030811] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0030824] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0030764] OMDb error: Request limit reached!

Downloading OMDb:  67%|██████▋   | 1005/1500 [00:48<00:23, 20.66movie/s]

17:00:05 | ERROR | [tt0030845] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0030848] OMDb error: Request limit reached!

Downloading OMDb:  67%|██████▋   | 1010/1500 [00:48<00:23, 20.59movie/s]

17:00:05 | ERROR | [tt0030857] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0030865] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0030944] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0030879] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0030989] OMDb error: Request limit reached!

Downloading OMDb:  68%|██████▊   | 1015/1500 [00:48<00:23, 20.73movie/s]

17:00:05 | ERROR | [tt0030993] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0030996] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0031002] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0031020] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0031022] OMDb error: Request limit reached!

Downloading OMDb:  68%|██████▊   | 1020/1500 [00:49<00:22, 20.90movie/s]

17:00:05 | ERROR | [tt0031033] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0031047] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0031058] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0031060] OMDb error: Request limit reached!

17:00:05 | ERROR | [tt0031066] OMDb error: Request limit reached!

Downloading OMDb:  68%|██████▊   | 1025/1500 [00:49<00:22, 20.96movie/s]

17:00:06 | ERROR | [tt0031088] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031067] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031143] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031147] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031148] OMDb error: Request limit reached!

Downloading OMDb:  69%|██████▊   | 1030/1500 [00:49<00:22, 20.99movie/s]

17:00:06 | ERROR | [tt0031149] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031173] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031208] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031210] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031215] OMDb error: Request limit reached!

Downloading OMDb:  69%|██████▉   | 1035/1500 [00:49<00:22, 21.06movie/s]

17:00:06 | ERROR | [tt0031225] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031235] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031252] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031259] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031260] OMDb error: Request limit reached!

Downloading OMDb:  69%|██████▉   | 1040/1500 [00:50<00:21, 21.03movie/s]

17:00:06 | ERROR | [tt0031289] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031302] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031309] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031314] OMDb error: Request limit reached!

17:00:06 | ERROR | [tt0031322] OMDb error: Request limit reached!

Downloading OMDb:  70%|██████▉   | 1045/1500 [00:50<00:21, 21.01movie/s]

17:00:07 | ERROR | [tt0031346] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031334] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031359] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031377] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031381] OMDb error: Request limit reached!

Downloading OMDb:  70%|███████   | 1050/1500 [00:50<00:21, 20.93movie/s]

17:00:07 | ERROR | [tt0031387] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031385] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031397] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031448] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031398] OMDb error: Request limit reached!

Downloading OMDb:  70%|███████   | 1055/1500 [00:50<00:21, 20.98movie/s]

17:00:07 | ERROR | [tt0031455] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031473] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031470] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031477] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031491] OMDb error: Request limit reached!

Downloading OMDb:  71%|███████   | 1060/1500 [00:51<00:20, 21.03movie/s]

17:00:07 | ERROR | [tt0031500] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031505] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031507] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031514] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031516] OMDb error: Request limit reached!

Downloading OMDb:  71%|███████   | 1065/1500 [00:51<00:20, 21.09movie/s]

17:00:07 | ERROR | [tt0031536] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031580] OMDb error: Request limit reached!

17:00:07 | ERROR | [tt0031593] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031602] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031614] OMDb error: Request limit reached!

Downloading OMDb:  71%|███████▏  | 1070/1500 [00:51<00:20, 21.14movie/s]

17:00:08 | ERROR | [tt0031619] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031647] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031679] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031678] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031680] OMDb error: Request limit reached!

Downloading OMDb:  72%|███████▏  | 1075/1500 [00:51<00:20, 21.19movie/s]

17:00:08 | ERROR | [tt0031704] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031708] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031709] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031725] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031742] OMDb error: Request limit reached!

Downloading OMDb:  72%|███████▏  | 1080/1500 [00:52<00:19, 21.08movie/s]

17:00:08 | ERROR | [tt0031750] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031747] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031754] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031762] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031796] OMDb error: Request limit reached!

Downloading OMDb:  72%|███████▏  | 1085/1500 [00:52<00:19, 21.16movie/s]

17:00:08 | ERROR | [tt0031826] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031831] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031835] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031842] OMDb error: Request limit reached!

17:00:08 | ERROR | [tt0031851] OMDb error: Request limit reached!

Downloading OMDb:  73%|███████▎  | 1090/1500 [00:52<00:19, 21.18movie/s]

17:00:09 | ERROR | [tt0031867] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0031885] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0031890] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0031891] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0031951] OMDb error: Request limit reached!

Downloading OMDb:  73%|███████▎  | 1095/1500 [00:52<00:19, 21.16movie/s]

17:00:09 | ERROR | [tt0031971] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0031968] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0031973] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0031976] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0031981] OMDb error: Request limit reached!

Downloading OMDb:  73%|███████▎  | 1100/1500 [00:52<00:18, 21.10movie/s]

17:00:09 | ERROR | [tt0031983] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0032007] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0031995] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0032022] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0032043] OMDb error: Request limit reached!

Downloading OMDb:  74%|███████▎  | 1105/1500 [00:53<00:18, 21.13movie/s]

17:00:09 | ERROR | [tt0032049] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0032080] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0032143] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0032138] OMDb error: Request limit reached!

17:00:09 | ERROR | [tt0032145] OMDb error: Request limit reached!

Downloading OMDb:  74%|███████▍  | 1109/1500 [00:53<00:18, 21.11movie/s]

17:00:10 | ERROR | [tt0032152] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032155] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032153] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032156] OMDb error: Request limit reached!

Downloading OMDb:  74%|███████▍  | 1114/1500 [00:53<00:19, 19.73movie/s]

17:00:10 | ERROR | [tt0032194] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032181] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032206] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032186] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032179] OMDb error: Request limit reached!

Downloading OMDb:  75%|███████▍  | 1119/1500 [00:53<00:18, 20.22movie/s]

17:00:10 | ERROR | [tt0032209] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032220] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032234] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032221] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032215] OMDb error: Request limit reached!

Downloading OMDb:  75%|███████▍  | 1124/1500 [00:54<00:18, 20.56movie/s]

17:00:10 | ERROR | [tt0032245] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032258] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032247] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032264] OMDb error: Request limit reached!

17:00:10 | ERROR | [tt0032273] OMDb error: Request limit reached!

Downloading OMDb:  75%|███████▌  | 1129/1500 [00:54<00:17, 20.75movie/s]

17:00:11 | ERROR | [tt0032281] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032283] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032284] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032285] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032290] OMDb error: Request limit reached!

Downloading OMDb:  76%|███████▌  | 1134/1500 [00:54<00:17, 20.92movie/s]

17:00:11 | ERROR | [tt0032315] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032324] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032325] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032326] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032338] OMDb error: Request limit reached!

Downloading OMDb:  76%|███████▌  | 1139/1500 [00:54<00:17, 21.00movie/s]

17:00:11 | ERROR | [tt0032339] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032342] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032349] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032356] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032376] OMDb error: Request limit reached!

Downloading OMDb:  76%|███████▋  | 1144/1500 [00:55<00:16, 20.99movie/s]

17:00:11 | ERROR | [tt0032383] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032397] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032390] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032404] OMDb error: Request limit reached!

17:00:11 | ERROR | [tt0032410] OMDb error: Request limit reached!

Downloading OMDb:  77%|███████▋  | 1149/1500 [00:55<00:16, 21.09movie/s]

17:00:12 | ERROR | [tt0032412] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032413] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032432] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032447] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032455] OMDb error: Request limit reached!

Downloading OMDb:  77%|███████▋  | 1154/1500 [00:55<00:16, 21.17movie/s]

17:00:12 | ERROR | [tt0032457] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032467] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032475] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032484] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032520] OMDb error: Request limit reached!

Downloading OMDb:  77%|███████▋  | 1159/1500 [00:55<00:16, 21.20movie/s]

17:00:12 | ERROR | [tt0032536] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032551] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032553] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032554] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032599] OMDb error: Request limit reached!

Downloading OMDb:  78%|███████▊  | 1164/1500 [00:56<00:15, 21.19movie/s]

17:00:12 | ERROR | [tt0032610] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032612] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032617] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032635] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032636] OMDb error: Request limit reached!

Downloading OMDb:  78%|███████▊  | 1169/1500 [00:56<00:15, 21.10movie/s]

17:00:12 | ERROR | [tt0032637] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032643] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032651] OMDb error: Request limit reached!

17:00:12 | ERROR | [tt0032653] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032671] OMDb error: Request limit reached!

Downloading OMDb:  78%|███████▊  | 1174/1500 [00:56<00:15, 21.16movie/s]

17:00:13 | ERROR | [tt0032676] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032686] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032701] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032728] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032733] OMDb error: Request limit reached!

Downloading OMDb:  79%|███████▊  | 1179/1500 [00:56<00:15, 21.10movie/s]

17:00:13 | ERROR | [tt0032753] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032762] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032811] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032818] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032819] OMDb error: Request limit reached!

Downloading OMDb:  79%|███████▉  | 1184/1500 [00:57<00:14, 21.13movie/s]

17:00:13 | ERROR | [tt0032828] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032842] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032846] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032850] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032851] OMDb error: Request limit reached!

Downloading OMDb:  79%|███████▉  | 1189/1500 [00:57<00:14, 21.18movie/s]

17:00:13 | ERROR | [tt0032871] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032873] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032881] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032904] OMDb error: Request limit reached!

17:00:13 | ERROR | [tt0032910] OMDb error: Request limit reached!

Downloading OMDb:  80%|███████▉  | 1194/1500 [00:57<00:14, 21.17movie/s]

17:00:14 | ERROR | [tt0032943] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0032946] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0032963] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0032976] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0032981] OMDb error: Request limit reached!

Downloading OMDb:  80%|███████▉  | 1199/1500 [00:57<00:14, 21.19movie/s]

17:00:14 | ERROR | [tt0032983] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0032993] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033021] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033022] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033028] OMDb error: Request limit reached!

Downloading OMDb:  80%|████████  | 1204/1500 [00:57<00:14, 21.14movie/s]

17:00:14 | ERROR | [tt0033029] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033038] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033045] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033105] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033107] OMDb error: Request limit reached!

Downloading OMDb:  81%|████████  | 1209/1500 [00:58<00:13, 21.17movie/s]

17:00:14 | ERROR | [tt0033110] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033117] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033149] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033152] OMDb error: Request limit reached!

17:00:14 | ERROR | [tt0033153] OMDb error: Request limit reached!

Downloading OMDb:  81%|████████  | 1214/1500 [00:58<00:13, 21.20movie/s]

17:00:15 | ERROR | [tt0033159] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033173] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033174] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033175] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033221] OMDb error: Request limit reached!

Downloading OMDb:  81%|████████▏ | 1219/1500 [00:58<00:13, 21.17movie/s]

17:00:15 | ERROR | [tt0033226] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033238] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033253] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033254] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033283] OMDb error: Request limit reached!

Downloading OMDb:  82%|████████▏ | 1224/1500 [00:58<00:13, 21.02movie/s]

17:00:15 | ERROR | [tt0033289] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033314] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033317] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033373] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033383] OMDb error: Request limit reached!

Downloading OMDb:  82%|████████▏ | 1229/1500 [00:59<00:12, 21.03movie/s]

17:00:15 | ERROR | [tt0033388] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033389] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033397] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033407] OMDb error: Request limit reached!

17:00:15 | ERROR | [tt0033405] OMDb error: Request limit reached!

Downloading OMDb:  82%|████████▏ | 1234/1500 [00:59<00:12, 21.02movie/s]

17:00:16 | ERROR | [tt0033409] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033432] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033436] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033458] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033467] OMDb error: Request limit reached!

Downloading OMDb:  83%|████████▎ | 1239/1500 [00:59<00:12, 21.08movie/s]

17:00:16 | ERROR | [tt0033477] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033491] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033517] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033519] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033530] OMDb error: Request limit reached!

Downloading OMDb:  83%|████████▎ | 1244/1500 [00:59<00:12, 21.08movie/s]

17:00:16 | ERROR | [tt0033532] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033533] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033537] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033553] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033558] OMDb error: Request limit reached!

Downloading OMDb:  83%|████████▎ | 1250/1500 [01:00<00:11, 22.33movie/s]

17:00:16 | ERROR | [tt0033582] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033596] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033606] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033616] OMDb error: Request limit reached!

17:00:16 | ERROR | [tt0033563] OMDb error: Request limit reached!

Downloading OMDb:  84%|████████▎ | 1254/1500 [01:00<00:11, 22.12movie/s]

17:00:16 | ERROR | [tt0033627] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033650] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033654] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033660] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033676] OMDb error: Request limit reached!

Downloading OMDb:  84%|████████▍ | 1260/1500 [01:00<00:10, 22.15movie/s]

17:00:17 | ERROR | [tt0033677] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033686] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033704] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033712] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033717] OMDb error: Request limit reached!

Downloading OMDb:  84%|████████▍ | 1264/1500 [01:00<00:10, 22.04movie/s]

17:00:17 | ERROR | [tt0033722] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033723] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033726] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033727] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033728] OMDb error: Request limit reached!

Downloading OMDb:  85%|████████▍ | 1270/1500 [01:01<00:10, 22.13movie/s]

17:00:17 | ERROR | [tt0033729] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033754] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033740] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033760] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033766] OMDb error: Request limit reached!

Downloading OMDb:  85%|████████▍ | 1274/1500 [01:01<00:10, 21.97movie/s]

17:00:17 | ERROR | [tt0033774] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033781] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033787] OMDb error: Request limit reached!

17:00:17 | ERROR | [tt0033802] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033803] OMDb error: Request limit reached!

Downloading OMDb:  85%|████████▌ | 1280/1500 [01:01<00:10, 22.00movie/s]

17:00:18 | ERROR | [tt0033804] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033832] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033836] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033852] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033858] OMDb error: Request limit reached!

Downloading OMDb:  86%|████████▌ | 1284/1500 [01:01<00:09, 21.96movie/s]

17:00:18 | ERROR | [tt0033868] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033870] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033873] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033874] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033879] OMDb error: Request limit reached!

Downloading OMDb:  86%|████████▌ | 1290/1500 [01:02<00:09, 22.24movie/s]

17:00:18 | ERROR | [tt0033891] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033902] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033918] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033922] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033945] OMDb error: Request limit reached!

Downloading OMDb:  86%|████████▋ | 1294/1500 [01:02<00:09, 21.92movie/s]

17:00:18 | ERROR | [tt0033963] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033980] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0033987] OMDb error: Request limit reached!

17:00:18 | ERROR | [tt0034012] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034027] OMDb error: Request limit reached!

Downloading OMDb:  87%|████████▋ | 1300/1500 [01:02<00:08, 22.37movie/s]

17:00:19 | ERROR | [tt0034055] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034078] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034091] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034093] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034116] OMDb error: Request limit reached!

Downloading OMDb:  87%|████████▋ | 1304/1500 [01:02<00:09, 21.36movie/s]

17:00:19 | ERROR | [tt0034162] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034167] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034172] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034175] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034182] OMDb error: Request limit reached!

Downloading OMDb:  87%|████████▋ | 1310/1500 [01:03<00:08, 22.50movie/s]

17:00:19 | ERROR | [tt0034224] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034236] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034240] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034241] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034242] OMDb error: Request limit reached!

Downloading OMDb:  88%|████████▊ | 1314/1500 [01:03<00:08, 21.49movie/s]

17:00:19 | ERROR | [tt0034248] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034251] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034266] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034269] OMDb error: Request limit reached!

17:00:19 | ERROR | [tt0034272] OMDb error: Request limit reached!

Downloading OMDb:  88%|████████▊ | 1320/1500 [01:03<00:07, 22.80movie/s]

17:00:20 | ERROR | [tt0034273] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034274] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034277] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034281] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034297] OMDb error: Request limit reached!

Downloading OMDb:  88%|████████▊ | 1324/1500 [01:03<00:08, 21.38movie/s]

17:00:20 | ERROR | [tt0034298] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034299] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034303] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034328] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034370] OMDb error: Request limit reached!

Downloading OMDb:  89%|████████▊ | 1330/1500 [01:03<00:07, 22.98movie/s]

17:00:20 | ERROR | [tt0034384] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034386] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034389] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034398] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034399] OMDb error: Request limit reached!

Downloading OMDb:  89%|████████▉ | 1334/1500 [01:04<00:07, 21.30movie/s]

17:00:20 | ERROR | [tt0034405] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034409] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034415] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034424] OMDb error: Request limit reached!

17:00:20 | ERROR | [tt0034428] OMDb error: Request limit reached!

Downloading OMDb:  89%|████████▉ | 1340/1500 [01:04<00:07, 22.71movie/s]

17:00:21 | ERROR | [tt0034449] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034461] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034465] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034478] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034485] OMDb error: Request limit reached!

Downloading OMDb:  90%|████████▉ | 1344/1500 [01:04<00:07, 21.13movie/s]

17:00:21 | ERROR | [tt0034492] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034513] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034493] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034514] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034521] OMDb error: Request limit reached!

Downloading OMDb:  90%|█████████ | 1350/1500 [01:04<00:06, 22.54movie/s]

17:00:21 | ERROR | [tt0034522] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034540] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034546] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034578] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034583] OMDb error: Request limit reached!

Downloading OMDb:  90%|█████████ | 1353/1500 [01:05<00:06, 21.24movie/s]

17:00:21 | ERROR | [tt0034586] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034587] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034591] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034622] OMDb error: Request limit reached!

Downloading OMDb:  91%|█████████ | 1359/1500 [01:05<00:06, 20.89movie/s]

17:00:21 | ERROR | [tt0034646] OMDb error: Request limit reached!

17:00:21 | ERROR | [tt0034613] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034694] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034711] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034716] OMDb error: Request limit reached!

Downloading OMDb:  91%|█████████ | 1363/1500 [01:05<00:06, 20.15movie/s]

17:00:22 | ERROR | [tt0034717] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034732] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034734] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034742] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034746] OMDb error: Request limit reached!

Downloading OMDb:  91%|█████████▏| 1369/1500 [01:05<00:05, 22.30movie/s]

17:00:22 | ERROR | [tt0034770] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034778] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034780] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034786] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034798] OMDb error: Request limit reached!

Downloading OMDb:  92%|█████████▏| 1373/1500 [01:06<00:06, 21.12movie/s]

17:00:22 | ERROR | [tt0034808] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034828] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034856] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034862] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034881] OMDb error: Request limit reached!

Downloading OMDb:  92%|█████████▏| 1379/1500 [01:06<00:05, 22.68movie/s]

17:00:22 | ERROR | [tt0034889] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034890] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034891] OMDb error: Request limit reached!

17:00:22 | ERROR | [tt0034902] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0034919] OMDb error: Request limit reached!

Downloading OMDb:  92%|█████████▏| 1383/1500 [01:06<00:05, 21.38movie/s]

17:00:23 | ERROR | [tt0034922] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0034923] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0034936] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0034928] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0034941] OMDb error: Request limit reached!

Downloading OMDb:  93%|█████████▎| 1389/1500 [01:06<00:04, 22.93movie/s]

17:00:23 | ERROR | [tt0034946] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0034965] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035009] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035015] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035017] OMDb error: Request limit reached!

Downloading OMDb:  93%|█████████▎| 1393/1500 [01:07<00:04, 21.52movie/s]

17:00:23 | ERROR | [tt0035019] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035020] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035034] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035082] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035093] OMDb error: Request limit reached!

Downloading OMDb:  93%|█████████▎| 1399/1500 [01:07<00:04, 23.13movie/s]

17:00:23 | ERROR | [tt0035096] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035100] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035105] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035124] OMDb error: Request limit reached!

17:00:23 | ERROR | [tt0035140] OMDb error: Request limit reached!

Downloading OMDb:  94%|█████████▎| 1403/1500 [01:07<00:04, 20.23movie/s]

17:00:24 | ERROR | [tt0035151] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035153] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035160] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035157] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035169] OMDb error: Request limit reached!

Downloading OMDb:  94%|█████████▍| 1409/1500 [01:07<00:03, 23.55movie/s]

17:00:24 | ERROR | [tt0035173] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035195] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035209] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035211] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035228] OMDb error: Request limit reached!

Downloading OMDb:  94%|█████████▍| 1413/1500 [01:07<00:04, 20.22movie/s]

17:00:24 | ERROR | [tt0035238] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035244] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035252] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035250] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035258] OMDb error: Request limit reached!

Downloading OMDb:  95%|█████████▍| 1418/1500 [01:08<00:04, 19.38movie/s]

17:00:24 | ERROR | [tt0035259] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035262] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035272] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035279] OMDb error: Request limit reached!

17:00:24 | ERROR | [tt0035317] OMDb error: Request limit reached!

Downloading OMDb:  95%|█████████▍| 1423/1500 [01:08<00:03, 20.05movie/s]

17:00:25 | ERROR | [tt0035318] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035356] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035360] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035369] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035415] OMDb error: Request limit reached!

Downloading OMDb:  95%|█████████▌| 1428/1500 [01:08<00:03, 20.44movie/s]

17:00:25 | ERROR | [tt0035417] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035419] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035423] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035429] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035431] OMDb error: Request limit reached!

Downloading OMDb:  96%|█████████▌| 1433/1500 [01:08<00:03, 20.57movie/s]

17:00:25 | ERROR | [tt0035432] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035446] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035447] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035460] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035489] OMDb error: Request limit reached!

Downloading OMDb:  96%|█████████▌| 1438/1500 [01:09<00:02, 20.72movie/s]

17:00:25 | ERROR | [tt0035521] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035530] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035567] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035555] OMDb error: Request limit reached!

17:00:25 | ERROR | [tt0035575] OMDb error: Request limit reached!

Downloading OMDb:  96%|█████████▌| 1443/1500 [01:09<00:02, 20.86movie/s]

17:00:26 | ERROR | [tt0035583] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035605] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035608] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035612] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035616] OMDb error: Request limit reached!

Downloading OMDb:  97%|█████████▋| 1448/1500 [01:09<00:02, 20.91movie/s]

17:00:26 | ERROR | [tt0035617] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035636] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035659] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035640] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035664] OMDb error: Request limit reached!

Downloading OMDb:  97%|█████████▋| 1453/1500 [01:09<00:02, 20.94movie/s]

17:00:26 | ERROR | [tt0035665] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035679] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035675] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035703] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035706] OMDb error: Request limit reached!

Downloading OMDb:  97%|█████████▋| 1458/1500 [01:10<00:01, 21.03movie/s]

17:00:26 | ERROR | [tt0035713] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035746] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035751] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035753] OMDb error: Request limit reached!

17:00:26 | ERROR | [tt0035763] OMDb error: Request limit reached!

Downloading OMDb:  98%|█████████▊| 1463/1500 [01:10<00:01, 21.04movie/s]

17:00:26 | ERROR | [tt0035769] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035770] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035777] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035784] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035790] OMDb error: Request limit reached!

Downloading OMDb:  98%|█████████▊| 1468/1500 [01:10<00:01, 21.07movie/s]

17:00:27 | ERROR | [tt0035795] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035798] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035799] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035800] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035829] OMDb error: Request limit reached!

Downloading OMDb:  98%|█████████▊| 1473/1500 [01:10<00:01, 21.09movie/s]

17:00:27 | ERROR | [tt0035855] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035860] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035884] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035881] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035885] OMDb error: Request limit reached!

Downloading OMDb:  99%|█████████▊| 1478/1500 [01:11<00:01, 21.10movie/s]

17:00:27 | ERROR | [tt0035896] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035899] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035916] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035937] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035939] OMDb error: Request limit reached!

Downloading OMDb:  99%|█████████▉| 1483/1500 [01:11<00:00, 21.02movie/s]

17:00:27 | ERROR | [tt0035942] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035951] OMDb error: Request limit reached!

17:00:27 | ERROR | [tt0035957] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0035958] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0035959] OMDb error: Request limit reached!

Downloading OMDb:  99%|█████████▉| 1488/1500 [01:11<00:00, 21.04movie/s]

17:00:28 | ERROR | [tt0035962] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0035966] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0035979] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0036004] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0035980] OMDb error: Request limit reached!

Downloading OMDb: 100%|█████████▉| 1493/1500 [01:11<00:00, 21.01movie/s]

17:00:28 | ERROR | [tt0036005] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0036009] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0036022] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0036027] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0036037] OMDb error: Request limit reached!

Downloading OMDb: 100%|█████████▉| 1498/1500 [01:11<00:00, 21.05movie/s]

17:00:28 | ERROR | [tt0036038] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0036047] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0036055] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0036092] OMDb error: Request limit reached!

17:00:28 | ERROR | [tt0036094] OMDb error: Request limit reached!

Downloading OMDb: 100%|██████████| 1500/1500 [01:12<00:00, 20.78movie/s]

17:00:28 | ERROR | [tt0036098] OMDb error: Request limit reached!

17:00:28 | SUCCESS | Download complete.

17:00:28 | INFO | Results appended to ../data/omdb_raw.jsonl